version: "3"

services:
  cacti:
    build:
      context: .
      args:
        - cacti_ver=1.1.38
    env_file:
     - .web-variables.env
    ports:
     - "8000:80"
#    - "161:161"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./rra/:/usr/share/cacti/rra
    restart: on-failure
