version: "3"

services:
  cacti:
#   image: dstw/cacti:1
    build:
      context: .
    image: dstw/cacti:2
    container_name: cacti
    env_file:
     - .web-variables.env
    ports:
     - "80:80"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./rra/:/usr/share/cacti/rra
    restart: on-failure
